[package]
name = "media"
version = "0.0.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["http2"] }
axum-server = "0.6.0"
blake3 = { version = "1.5", features = ["serde"] }
camino = "1.1"
ciborium = "0.2.2"
clap = { version = "4.5", features = ["derive"] }
hex = "0.4.3"
libc = "0.2.155"
mime_guess = "2.0.4"
regex = "1.10.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.119"
serde_yaml = "0.9.34"
snafu = { version = "0.8.3", features = ["backtrace"] }
tempfile = "3.10.1"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
walkdir = "2.5"
