[package]
name = "media"
version = "0.0.0"
edition = "2021"

[dependencies]
blake3 = { version = "1.5.0", features = ["serde"] }
ciborium = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.15"
strum = { version = "0.26.3", features = ["derive"] }
