[package]
name = "library"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
media = { path = "../media" }
hypermedia = { path = "../hypermedia" }

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "DomStringMap",
  "PointerEvent",
  "HtmlButtonElement",
  "HtmlIFrameElement",
]
